seeder:
  pages:
    - url: "https://joker.no/varer"
      page_type: "categories"

parsers:
  - page_type: categories
    file: "./parsers/categories.rb"
    disabled: false
    outputs:
      - name: "category_links"
        fields:
          - name: "category_name"
            description: "name of the category"
            selector: ""
          - name: "category_url"
            description: "URL link to the category page"
            selector: ""
    pages:
      - url: "https://joker.no/varer/hus-hjem-artikler"
        page_type: "subcategories"

  - page_type: subcategories
    file: "./parsers/subcategories.rb"
    disabled: false
    outputs:
      - name: "subcategory_links"
        fields:
          - name: "subcategory_name"
            description: "name of the subcategory"
            selector: ""
          - name: "subcategory_url"
            description: "URL link to the subcategory page"
            selector: ""
    pages:
      - url: "https://joker.no/varer/hus-hjem-artikler/grill-og-ild"
        page_type: "listings"

  - page_type: listings
    file: "./parsers/listings.rb"
    disabled: false
    outputs:
      - name: "products"
        fields:
          - name: "competitor_product_id"
            description: "unique product identifier from competitor"
            selector: ""
          - name: "name"
            description: "product name/title"
            selector: ""
          - name: "brand"
            description: "product brand"
            selector: ""
          - name: "category"
            description: "main product category"
            selector: ""
          - name: "sub_category"
            description: "product subcategory"
            selector: ""
          - name: "customer_price_lc"
            description: "current selling price in local currency"
            selector: ""
          - name: "base_price_lc"
            description: "original price before discounts"
            selector: ""
          - name: "has_discount"
            description: "whether the product has a discount"
            selector: ""
          - name: "discount_percentage"
            description: "discount percentage if applicable"
            selector: ""
          - name: "rank_in_listing"
            description: "position of product in the listing"
            selector: ""
          - name: "page_number"
            description: "page number in pagination"
            selector: ""
          - name: "product_pieces"
            description: "number of pieces in the product"
            selector: ""
          - name: "size_std"
            description: "standardized size value"
            selector: ""
          - name: "size_unit_std"
            description: "standardized size unit"
            selector: ""
          - name: "description"
            description: "product description"
            selector: ""
          - name: "img_url"
            description: "main product image URL"
            selector: ""
          - name: "barcode"
            description: "product barcode/EAN"
            selector: ""
          - name: "sku"
            description: "product SKU"
            selector: ""
          - name: "url"
            description: "product page URL"
            selector: ""
          - name: "is_available"
            description: "whether product is in stock"
            selector: ""
          - name: "is_promoted"
            description: "whether product has promotional offers"
            selector: ""
          - name: "type_of_promotion"
            description: "type of promotion applied"
            selector: ""
          - name: "promo_attributes"
            description: "promotional details and attributes"
            selector: ""
          - name: "is_private_label"
            description: "whether product is private label"
            selector: ""
          - name: "reviews"
            description: "product reviews information"
            selector: ""
          - name: "item_attributes"
            description: "additional product attributes like dietary info"
            selector: ""
          - name: "item_identifiers"
            description: "product identifiers and codes"
            selector: ""
          - name: "country_of_origin"
            description: "country where product was manufactured"
            selector: ""
          - name: "variants"
            description: "product variants and options"
            selector: ""
